NUMPY

INTRODUCTION 

* Python library for creating n dimensiiona arrays 
* Built in linear algebra , trigonometric and random number capabilities

WHY NUMPY??

* Efficient than lists
* Due to broadcasting capabilities


NUMPY ARRAY

In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
mylist

[1, 2, 3]

In [6]:
myarr = np.array(mylist)

In [7]:
myarr

array([1, 2, 3])

In [8]:
type(myarr)

numpy.ndarray

In [9]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

BUILT- IN FUNCTIONS 

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.linspace(0,10,3) #END POINT IS INCLUDED

array([ 0.,  5., 10.])

In [21]:
np.linspace(0,10,2)

array([ 0., 10.])

In [22]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [23]:
len(np.linspace(0,10,11))

11

In [24]:
np.eye(5) # IDENTITY MATRIX 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.random.rand(1)

array([0.75041673])

In [26]:
np.random.rand(5,6)

array([[0.99206689, 0.03098865, 0.33554858, 0.61981954, 0.36383096,
        0.29717575],
       [0.03382225, 0.30271094, 0.1237177 , 0.30650853, 0.77395333,
        0.6251099 ],
       [0.648173  , 0.7669033 , 0.90833954, 0.86150403, 0.14906309,
        0.22061806],
       [0.64410336, 0.08619248, 0.46350263, 0.01039155, 0.32025374,
        0.98033769],
       [0.91179695, 0.65944307, 0.41288691, 0.8839307 , 0.49869164,
        0.68288333]])

In [27]:
np.random.rand(5,2)

array([[0.32249014, 0.90963873],
       [0.51387701, 0.37354874],
       [0.43357314, 0.96180523],
       [0.98699792, 0.35181199],
       [0.14384136, 0.94811424]])

In [28]:
np.random.randn(10) # MEAN = 0 && VARIANCE = 1

array([-0.08663342, -0.07839718, -0.31068335, -0.97376418,  0.2971883 ,
       -0.18309239,  1.66183133,  1.31488107, -0.5985129 , -0.03588942])

In [29]:
np.random.randn(2,3)

array([[-1.86483762,  0.37942728, -0.3563532 ],
       [ 0.75788996,  0.99603958, -0.33679957]])

In [30]:
np.random.randint(0,101,5)

array([92, 94, 66, 13, 83])

In [32]:
np.random.randint(0,101,(4,5))

array([[ 21,  20,  53,   6,   7],
       [  8,  24,  88,  25,  27],
       [ 39,  58,  48,  55,  15],
       [ 99,  66,  46,  25, 100]])

In [33]:
np.random.seed(42) # SET PARTICULAR RANDOM NUMBERS
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [55]:
arr = np.arange(0,25)

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [57]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [58]:
arr.reshape(5,4) # NOTE : CANNOT DO IT 

ValueError: cannot reshape array of size 25 into shape (5,4)

In [59]:
ranarr = np.random.randint(0,101,10)

In [60]:
ranarr

array([ 1, 87, 29, 37,  1, 63, 59, 20, 32, 75])

In [61]:
ranarr.max()

87

In [62]:
ranarr.min()

1

In [63]:
ranarr.argmax() #INDEX OF MAXX NUMBER

1

In [64]:
ranarr.argmin() #INDEX OF MIN NUMBER

0

In [65]:
ranarr.dtype 

dtype('int32')

In [66]:
arr.shape

(25,)

In [67]:
arr = arr.reshape(5,5)

In [68]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [70]:
arr.shape

(5, 5)

In [72]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [73]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])